version: "3.9"
services:
  api:
    build: .
    hostname: $(cookiecutter.repo_name)
    restart: always
    ports:
      - "8001:8001"
    environment:
      - ENV_STATE=DEV
      - DATABASE_URI=postgresql://${POSTGRES_DATABASE_USERNAME}:${POSTGRES_DATABASE_PASSWORD}@postgres:5432/${POSTGRES_DATABASE_NAME}
      # Add other environment variables here
    depends_on:
      - postgres
    networks:
      - app-network
    env_file:
      - .env

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_DATABASE_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
